exclude: |
    (?x)^(
        ^.*Dockerfile$
        |^.*\.txt$
        |^\.pre-commit-config\.yaml$
        |^\.gitignore$
        |^.*\.md$
        |^.*\.sh$
        |^.*\.env$
        |^.*\.envsample$
        |^.*\.ps1$
    )$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
        exclude_types: [text]
    -   id: check-added-large-files
        args: [--maxkb=500]
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
        args: ["--unsafe"]
    -   id: mixed-line-ending

-   repo: local
    hooks:
    -   id: flake8
        name: flake8_base
        entry: flake8
        args:
            [
                "--max-line-length=120",
            ]
        language: system
        exclude: |
            (?x)^(
                ^.*/tests/.*$
            )$

-   repo: local
    hooks:
    -   id: flake8
        name: flake8_tests
        entry: flake8
        args:
            [
                "--max-line-length=120",
                "--ignore=F811,F401"
            ]
        language: system
        files: |
            (?x)^(
                ^.*/tests/.*$
            )$

    -   id: isort
        name: isort
        entry: isort
        args:
            [
                "--multi-line", "3",
                "--fgw", "2",
                "--lai", "2",
                "--tc",
            ]
        language: system